# Generated by Django 5.2.7 on 2026-02-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AlterField(
            model_name='education',
            name='gpa',
            field=models.CharField(max_length=10),
        ),
    ]
