# Generated by Django 5.2.7 on 2026-02-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_education_description_education_cv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='speciality',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=20),
        ),
    ]
