# Generated by Django 5.2.7 on 2026-02-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_education_speciality_alter_education_end_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
