# Generated by Django 5.2.7 on 2026-02-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificate_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
