# Generated by Django 5.2.7 on 2026-02-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='projects/'),
        ),
    ]
